### ISSUE TITLE
can it be made to work with awesome-typescript-loader?

### ISSUE THREAD

**Issue by DustinWehr** [nippur72/ifdef-loader#1]
trying to just substitute awesome-typescript-loader for ts-loader, ifdef-loader runs fine, but awesome-typescript-loader doesn't see modified code.
https://github.com/s-panferov/awesome-typescript-loader

**Comment by nippur72** [comment]
have you tried enabling/disabling caching options in `awesome-typescript-loader` ?

From the `ifdef-loader` side, I have no clue on what to do, as it is a very basic loader, written directly from the webpack "examples".

**Comment by james-criscuolo** [comment]
I was able to get this working with `awesome-typescript-loader` by following the README.  I pass no arguments to ATL.
