### ISSUE TITLE
How to config ifdef-loader in jest

### ISSUE THREAD

**Issue by callblueday** [nippur72/ifdef-loader#12]
I use `ifdef-loader` in my project, and i want to use jest to do unit test. Is there any way to make jest         recognize ifdef slash?

**Comment by nippur72** [comment]
I don't know much about `jest`, but I think you have two options:
1) (the easiest one) bundle your `*.test.js` files in a debug build and run them from that big file

2) the hardest one: use the `transform` config option in jest to hook to the `parse` function in `ifdef-loader`, see
https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string
and
https://facebook.github.io/jest/docs/en/webpack.html
and
https://github.com/nippur72/ifdef-loader/blob/master/ifdef-loader.ts#L25

**Comment by callblueday** [comment]
Thanks a lot! @nippur72  I will try it.
