### ISSUE TITLE
[Feature Request] place condition into /**/

### ISSUE THREAD

**Issue by alexander-ossur** [nippur72/ifdef-loader#14]
Hi there,

There is a case when using TSX. Unfortunately triple slash wont work (or I am missing something). 

Usage example:
```javascript
class Test extends Component {
    render () {
        return (
            <div>
{/* #if __SERVER__ */}
		<ChannelsList />
{/* #endif */}
            </div>	
        );
    }
}
```

**Comment by Baldrs** [comment]
I'd vote to rename it to support conditional [JT]SX compilation

**Comment by nippur72** [comment]
@alexander-ossur triple slash does work as long as `ifdef-loader` is the one called first in the chain of loaders for the `.tsx` extension. That means placing it as the last element in the `loaders` array in webpack.

Note that if typescript gets called before `ifdef-loader` then there is chance of your comments being dropped out from the JavaScript output (and thus failing to be picked by `ifdef-loader`).

Example:
```
// this comment will not appear in the JavaScript output
interface someinterface {}

```
See https://github.com/Microsoft/TypeScript/issues/11242

**Comment by Baldrs** [comment]
Yes but it is not valid comment inside JSX, and thus support for JSX should be added separately

**Comment by shoesel** [comment]
How about adding the condition inside the `/*!`-block comment?
My JS-code is compiled with tsc which is configured to remove all comments (except those above).

**Comment by nippur72** [comment]
this issue can be addressed with the new option `fill-with-blanks` in 2.2.0.

Please reopen this issue if it doesn't.
