### ISSUE TITLE
Performance improvement: skip files

### ISSUE THREAD

**Issue by Cristy94** [nippur72/ifdef-loader#24]
While testing my (slow) webpack build process I noticed that `ifdef-loader` was taking a long time. Just had a quick look over the source code and think there are a lot of improvements that could be done.

First one, and easiest one, would be to skip files that don't contain the `// #if` string, before doing all the line splitting and going through all the lines.
https://github.com/nippur72/ifdef-loader/blob/df8ab2fc8283248e9bfc58570c9bedbe075452e7/preprocessor.ts#L38-L50

Could just add this before the splitting (line 42):
```
// Skip files that don't have ifdefs
if(!source.includes('// #if')) return source;
```

**Comment by nippur72** [comment]
sounds reasonable, I made PR #25 out of it (I used `indeOf` in place of `includes`).

Published as `ifdef-loader@2.1.2`

**Comment by wouldntsavezion** [comment]
PR #25 has been merged, this issue could be closed.

**Comment by Cristy94** [comment]
Thank you for the quick release! I will close this for now, if I see other improvements I will create a new issue.
